### PR TITLE
Modularize

### PR DESCRIPTION
**Pull request by mxcl**
Splits Sublimate into modules that mirror Vapor’s underlying module structure:

* SublimateNIO
* SublimateFluentKit
* SublimateVapor
* Sublimate

Each exports the previous so the changes are API safe.

Rationale: so I could be sure my base modules did not import Vapor, which has a whole bunch of global state manipulators and thus I felt made the whole app less testable. Now my base can depend on only SublimateFluentKit (which does not depend on Vapor).

The Sublimate module provides our freeform `sublimate` functions.

Recommend a major version bump, just in case.

### CODE REVIEW

**Comment by jhheider** [comment]
Smart. Time to fix the `llvm-cov` version issues, I think.

**Comment by jhheider** [comment]
I had to manually bring in `.product(name: "NIO", package: "swift-nio"),` after this change to satisfy SwiftPM, although it certainly doesn't _seem_ like _ should have to. SwiftPM not the most robust package system, unfortunately.

**Comment by jhheider** [comment]
> I had to manually bring in `.product(name: "NIO", package: "swift-nio"),` after this change to satisfy SwiftPM, although it certainly doesn't _seem_ like _ should have to. SwiftPM not the most robust package system, unfortunately.

And, after hours of dependency hell, `git reset`ting and starting fresh no longer required it. Freaking SwiftPM.

**Comment by mxcl** [comment]
Yeah I had this happen previously. “Reset package caches” would usually fix it.

**Pull request merged**
